### ISSUE TITLE
[Bug]: Can't find class with latest MelonLoader

### ISSUE THREAD

**Issue by Redict** [originalnicodr/UnityExplorer#59]
### Are you on the latest version of UnityExplorer?

- [X] Yes, I'm on the latest version of UnityExplorer.

### Which release are you using?

BepInEx IL2CPP

### Which game did this occur on?

Last Epoch

### Describe the issue.

Can't find any class in inspector
> [04:00:37.995] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
> Could not load type 'Win32_IN6_ADDR' from assembly 'Il2CppSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
>    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
>    at System.Reflection.Assembly.GetTypes()
>    at UnityExplorer.ObjectExplorer.SearchProvider.ClassSearch(String input)
>    at UnityExplorer.ObjectExplorer.ObjectSearch.DoSearch()
>    at UniverseLib.UI.Models.ButtonRef.<.ctor>b__14_0()
>    at (il2cpp delegate trampoline) System.Void_System.Action(IntPtr , Il2CppMethodInfo* )
> System.TypeLoadException: Could not load type 'Win32_IN6_ADDR' from assembly 'Il2CppSystem, Version=4.0.0.0, C

### Relevant log output

```shell
[03:59:31.783] ------------------------------
[03:59:31.784] UnityExplorer v4.11.1
[03:59:31.784] by Sinai, yukieiji
[03:59:31.784] Assembly: UnityExplorer.ML.IL2CPP.CoreCLR.dll
[03:59:31.784] ------------------------------
[03:59:31.784] [DEBUG] MelonAssembly 'UnityExplorer.ML.IL2CPP.CoreCLR' subscribed with LoaderInitialized
[03:59:31.784] [DEBUG] MelonAssembly 'UnityExplorer.ML.IL2CPP.CoreCLR' subscribed with OnLateInitializeMelon
[03:59:31.785] ------------------------------
[03:59:31.785] 1 Mod loaded.

[03:59:31.787] [DEBUG] [DotnetManagedFolder] Failed to find Il2CppInterop.HarmonySupport.dll in any of the known search directories
[03:59:31.958] [DEBUG] il2cpp_object_get_virtual_method: 0x7FFBA5C97520
[03:59:31.958] [DEBUG] Object::GetVirtualMethod: 0x7FFBA5CD57E0
[03:59:31.960] [DEBUG] GenericMethod::GetMethod: 0x7FFBA5D00890
[03:59:32.167] [DEBUG] il2cpp_image_get_class: 0x7FFBA5C972C0
[03:59:32.167] [DEBUG] Image::GetType: 0x7FFBA5CD3AA0
[03:59:32.168] [DEBUG] MetadataCache::GetTypeInfoFromTypeDefinitionIndex: 0x7FFBA5CD3B10
[03:59:32.276] [DEBUG] Class::GetDefaultFieldValue: 0x7FFBA5CCE1F0
[03:59:32.370] [DEBUG] Class::Init: 0x7FFBA5CD5FF0
[03:59:32.370] [DEBUG] il2cpp_class_from_il2cpp_type: 0x7FFBA5C96B80
[03:59:32.371] [DEBUG] Class::FromIl2CppType: 0x7FFBA5CC99C0
[03:59:32.371] [DEBUG] il2cpp_class_from_name: 0x7FFBA5C96B90
[03:59:32.371] [DEBUG] Class::FromName: 0x7FFBA5CC9BE0
[03:59:32.383] [DEBUG] [DotnetManagedFolder] Failed to find Il2CppSystem.Private.CoreLib.dll in any of the known search directories
[03:59:32.389] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[03:59:32.413] [DEBUG] [DotnetManagedFolder] Failed to find Il2CppSystem.Private.CoreLib.dll in any of the known search directories
[03:59:32.414] Registered mono type MelonLoader.Support.MonoEnumeratorWrapper in il2cpp domain
[03:59:32.415] [DEBUG] [DotnetManagedFolder] Failed to find Il2CppSystem.Private.CoreLib.dll in any of the known search directories
[03:59:32.416] Registered mono type MelonLoader.Support.SM_Component in il2cpp domain
[03:59:32.422] Support Module Loaded: C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Dependencies\SupportModules\Il2Cpp.dll
[03:59:32.438] [DEBUG] MelonAssembly 'UnityExplorer.ML.IL2CPP.CoreCLR' unsubscribed with HarmonyInit
[03:59:32.442] [UnityExplorer] UnityExplorer 4.11.1 initializing...
[03:59:32.454] [UnityExplorer] [UniverseLib] UniverseLib 1.5.5 initializing...
[03:59:32.455] [DEBUG] [DotnetManagedFolder] Failed to find Il2CppSystem.Private.CoreLib.dll in any of the known search directories
[03:59:32.457] Registered mono type UniverseLib.UniversalBehaviour in il2cpp domain
[03:59:32.601] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\UnityEngine.Physics2DModule.dll...
[03:59:32.622] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\UnityEngine.InputLegacyModule.dll...
[03:59:32.665] [DEBUG] [DotnetManagedFolder] Failed to find Il2CppSystem.Private.CoreLib.dll in any of the known search directories
[03:59:32.666] Registered mono type UniverseLib.Runtime.Il2Cpp.Il2CppManagedEnumerator in il2cpp domain
[03:59:32.676] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Unity.Mathematics.dll...
[03:59:32.683] [UnityExplorer] [UniverseLib] Finished UniverseLib initial setup.
[03:59:32.690] [DEBUG] [DotnetManagedFolder] Failed to find Il2CppSystem.Private.CoreLib.dll in any of the known search directories
[03:59:32.690] Registered mono type UnityExplorer.ExplorerBehaviour in il2cpp domain
[03:59:32.912] [UnityExplorer] Initialized UnityCrashPrevention for: Canvas.get_renderingDisplaySize
[03:59:33.137] [DEBUG] MelonAssembly 'UnityExplorer.ML.IL2CPP.CoreCLR' unsubscribed with LoaderInitialized
[03:59:33.882] [DEBUG] Unique Host Name or IP Found: lastepochpublic.blob.core.windows.net
[03:59:33.933] [DEBUG] Host Name or IP blocked: config.uca.cloud.unity3d.com
[03:59:34.171] [DEBUG] MelonAssembly 'UnityExplorer.ML.IL2CPP.CoreCLR' unsubscribed with OnLateInitializeMelon
[03:59:34.178] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Unity.Timeline.dll...
[03:59:34.228] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Il2CppSystem.dll...
[03:59:34.237] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Il2CppMono.Security.dll...
[03:59:34.257] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Il2CppSystem.Configuration.dll...
[03:59:34.258] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Il2CppSystem.Xml.dll...
[03:59:34.373] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Il2CppLE.dll...
[03:59:34.445] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Il2CppSirenix.Serialization.dll...
[03:59:34.447] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\UnityEngine.AnimationModule.dll...
[03:59:34.455] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Il2CppSirenix.Serialization.Config.dll...
[03:59:34.457] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Il2CppSirenix.Utilities.dll...
[03:59:34.474] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Unity.Addressables.dll...
[03:59:34.475] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Unity.ResourceManager.dll...
[03:59:34.479] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\UnityEngine.UnityWebRequestModule.dll...
[03:59:34.483] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\UnityEngine.VideoModule.dll...
[03:59:34.486] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Il2CppLE.Core.dll...
[03:59:34.492] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Unity.Postprocessing.Runtime.dll...
[03:59:34.500] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Unity.TextMeshPro.dll...
[03:59:34.503] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\UnityEngine.TextCoreModule.dll...
[03:59:34.511] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Il2CppLE.Networking.Core.dll...
[03:59:34.513] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Il2CppLidgren.Network.dll...
[03:59:34.515] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Il2CppNewtonsoft.Json.dll...
[03:59:34.540] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Unity.Networking.Transport.dll...
[03:59:34.542] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Il2CppUniTask.dll...
[03:59:34.546] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\UnityEngine.ParticleSystemModule.dll...
[03:59:34.552] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Il2CppLE.UI.Controls.dll...
[03:59:34.555] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Il2CppRewired_Core.dll...
[03:59:34.605] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Il2CppXNode.dll...
[03:59:34.608] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Il2CppPolly.dll...
[03:59:34.978] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\UnityEngine.AIModule.dll...
[03:59:35.191] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Il2CppUMA_Core.dll...
[03:59:35.268] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\Unity.Services.Core.dll...
[03:59:35.422] [UnityExplorer] [UniverseLib] Can't cache type named DragState Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.BaseField`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[03:59:35.423] [UnityExplorer] [UniverseLib] Can't cache type named <>c Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.TypedUxmlAttributeDescription`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[03:59:35.424] [UnityExplorer] [UniverseLib] Can't cache type named <>c Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.TypedUxmlAttributeDescription`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[03:59:35.424] [UnityExplorer] [UniverseLib] Can't cache type named <>c Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.TypedUxmlAttributeDescription`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[03:59:35.424] [UnityExplorer] [UniverseLib] Can't cache type named <>c Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.TypedUxmlAttributeDescription`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[03:59:35.424] [UnityExplorer] [UniverseLib] Can't cache type named <>c Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.TypedUxmlAttributeDescription`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[03:59:35.424] [UnityExplorer] [UniverseLib] Can't cache type named <>c Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.TypedUxmlAttributeDescription`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[03:59:35.425] [UnityExplorer] [UniverseLib] Can't cache type named <>c Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.TypedUxmlAttributeDescription`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[03:59:35.425] [UnityExplorer] [UniverseLib] Can't cache type named <>c Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.UIR.ShaderInfoStorage`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[03:59:35.425] [UnityExplorer] [UniverseLib] Can't cache type named <>c Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.UIR.ShaderInfoStorage`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[03:59:35.425] [UnityExplorer] [UniverseLib] Can't cache type named <>c Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.UIR.LinkedPool`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[03:59:35.426] [UnityExplorer] [UniverseLib] Can't cache type named <>c Error: System.TypeLoadException: Could not load type 'UnityEngine.UIElements.UIR.LinkedPool`1' from assembly 'UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetDeclaringType(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.GetEnclosingType()
   at System.RuntimeType.RuntimeTypeCache.GetNameSpace()
   at System.RuntimeType.get_Namespace()
   at UniverseLib.ReflectionUtility.CacheTypes(Assembly asm)
[03:59:35.458] [DEBUG] [DotnetManagedFolder] Loading from C:\Program Files (x86)\Steam\steamapps\common\Last Epoch\MelonLoader\Il2CppAssemblies\UnityEngine.XRModule.dll...
[03:59:35.466] [UnityExplorer] [UniverseLib] Loaded Unhollowed modules in 2,798 seconds.
[03:59:35.582] [UnityExplorer] [UniverseLib] Setup deobfuscation cache in 0,116000004 seconds.
[03:59:35.585] [UnityExplorer] [UniverseLib] Initialized Legacy Input support
[03:59:35.873] [UnityExplorer] [UniverseLib] 	 IL2CPP method has no corresponding pointer, aborting patch of UnityEngine.AssetBundle.UnloadAllAssetBundles
[03:59:35.885] [DEBUG] [DotnetManagedFolder] Failed to find Il2CppSystem.Private.CoreLib.dll in any of the known search directories
[03:59:35.885] Registered mono type UniverseLib.AssetBundle in il2cpp domain
[03:59:37.859] [UnityExplorer] [UniverseLib] Loaded modern bundle for Unity 2019.4.40f1
[03:59:38.941] [UnityExplorer] [UniverseLib] UniverseLib 1.5.5 initialized.
[03:59:38.944] [UnityExplorer] Creating UI...
[03:59:39.378] [UnityExplorer] UnityExplorer 4.11.1 (IL2CPP) initialized.
[03:59:39.413] [DEBUG] [DotnetManagedFolder] Failed to find Il2CppSystem.Private.CoreLib.dll in any of the known search directories
[03:59:39.414] Registered mono type UnityExplorer.KeypressListener in il2cpp domain
[03:59:39.492] [DEBUG] Host Name or IP blocked: cdp.cloud.unity3d.com
[03:59:39.735] [DEBUG] Host Name or IP blocked: perf-events.cloud.unity3d.com
[03:59:39.735] [DEBUG] Host Name or IP blocked: perf-events.cloud.unity3d.com
[03:59:41.555] [DEBUG] Unique Host Name or IP Found: collect.analytics.unity3d.com
[03:59:47.926] [DEBUG] Unique Host Name or IP Found: df4fe.playfabapi.com
[03:59:59.188] [DEBUG] [DotnetManagedFolder] Failed to find System.Reflection.Metadata.resources.dll in any of the known search directories
[03:59:59.189] [DEBUG] [DotnetManagedFolder] Failed to find System.Reflection.Metadata.resources.dll in any of the known search directories
[03:59:59.190] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'Win32_IN6_ADDR' from assembly 'Il2CppSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at UnityExplorer.ObjectExplorer.SearchProvider.ClassSearch(String input)
   at UnityExplorer.ObjectExplorer.ObjectSearch.DoSearch()
   at UniverseLib.UI.Models.ButtonRef.<.ctor>b__14_0()
   at (il2cpp delegate trampoline) System.Void_System.Action(IntPtr , Il2CppMethodInfo* )
System.TypeLoadException: Could not load type 'Win32_IN6_ADDR' from assembly 'Il2CppSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
[04:00:01.159] [DEBUG] Unique Host Name or IP Found: lastepoch-data-nld-prod.documents.azure.com
[04:00:15.569] [DEBUG] [DotnetManagedFolder] Failed to find System.Net.Sockets.resources.dll in any of the known search directories
                                                                                                                                ies
[04:00:15.570] [DEBUG] [DotnetManagedFolder] Failed to find System.Net.Sockets.resources.dll in any of the known search directories
[04:00:15.570] [DEBUG] [DotnetManagedFolder] Failed to find System.Net.Sockets.resources.dll in any of the known search directories
[04:00:32.238] [DEBUG] Unique Host Name or IP Found: api-b201c900-1e6d-4ede-858b-8707e4ee646b.sendbird.com
[04:00:32.240] [DEBUG] Unique Host Name or IP Found: ws-b201c900-1e6d-4ede-858b-8707e4ee646b.sendbird.com
[04:00:36.308] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'Win32_IN6_ADDR' from assembly 'Il2CppSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at UnityExplorer.ObjectExplorer.SearchProvider.ClassSearch(String input)
   at UnityExplorer.ObjectExplorer.ObjectSearch.DoSearch()
   at UniverseLib.UI.Models.ButtonRef.<.ctor>b__14_0()
   at (il2cpp delegate trampoline) System.Void_System.Action(IntPtr , Il2CppMethodInfo* )
System.TypeLoadException: Could not load type 'Win32_IN6_ADDR' from assembly 'Il2CppSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
[04:00:37.261] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'Win32_IN6_ADDR' from assembly 'Il2CppSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at UnityExplorer.ObjectExplorer.SearchProvider.ClassSearch(String input)
   at UnityExplorer.ObjectExplorer.ObjectSearch.DoSearch()
   at UniverseLib.UI.Models.ButtonRef.<.ctor>b__14_0()
   at (il2cpp delegate trampoline) System.Void_System.Action(IntPtr , Il2CppMethodInfo* )
System.TypeLoadException: Could not load type 'Win32_IN6_ADDR' from assembly 'Il2CppSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
[04:00:37.657] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'Win32_IN6_ADDR' from assembly 'Il2CppSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at UnityExplorer.ObjectExplorer.SearchProvider.ClassSearch(String input)
   at UnityExplorer.ObjectExplorer.ObjectSearch.DoSearch()
   at UniverseLib.UI.Models.ButtonRef.<.ctor>b__14_0()
   at (il2cpp delegate trampoline) System.Void_System.Action(IntPtr , Il2CppMethodInfo* )
System.TypeLoadException: Could not load type 'Win32_IN6_ADDR' from assembly 'Il2CppSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
[04:00:37.852] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'Win32_IN6_ADDR' from assembly 'Il2CppSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at UnityExplorer.ObjectExplorer.SearchProvider.ClassSearch(String input)
   at UnityExplorer.ObjectExplorer.ObjectSearch.DoSearch()
   at UniverseLib.UI.Models.ButtonRef.<.ctor>b__14_0()
   at (il2cpp delegate trampoline) System.Void_System.Action(IntPtr , Il2CppMethodInfo* )
System.TypeLoadException: Could not load type 'Win32_IN6_ADDR' from assembly 'Il2CppSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
[04:00:37.995] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'Win32_IN6_ADDR' from assembly 'Il2CppSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at UnityExplorer.ObjectExplorer.SearchProvider.ClassSearch(String input)
   at UnityExplorer.ObjectExplorer.ObjectSearch.DoSearch()
   at UniverseLib.UI.Models.ButtonRef.<.ctor>b__14_0()
   at (il2cpp delegate trampoline) System.Void_System.Action(IntPtr , Il2CppMethodInfo* )
System.TypeLoadException: Could not load type 'Win32_IN6_ADDR' from assembly 'Il2CppSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' because the format is invalid.
[04:01:24.483] [DEBUG] Host Name or IP blocked: cdp.cloud.unity3d.com
[04:01:26.554] [DEBUG] Unique Host Name or IP Found: lastepoch-data-prod.documents.azure.com
```

**Comment by Redict** [comment]
@originalnicodr Hi, can you assist?

**Comment by originalnicodr** [comment]
Hey there! Even tho this is a fork of UnityExplorer I don't tend to focus on updating UnityExplorer compatibility in new games myself as it involves... quite a bit of knowledge about Unity, HarmonyX, and C#, which I lack (in the process of making that clearer on the readme). But I am thinking of a few things that you could try:

- Try the BepInEx builds instead of the MelonLoader one:
  - [UnityExplorer.BepInEx.IL2CPP.CoreCLR.zip](https://github.com/originalnicodr/UnityExplorer/actions/runs/7983464871/artifacts/1261634589)
  - [UnityExplorer.BepInEx.Unity.IL2CPP.CoreCLR.zip](https://github.com/originalnicodr/UnityExplorer/actions/runs/7983464871/artifacts/1261634592)
 I am not sure how experimental/untested CoreCRL builds are, as I have not tested any game with that.
- Given that I updated my fork with the awesome work yukieiji has done over [theirs](https://github.com/yukieiji/UnityExplorer) I would recommend asking them about it. Not trying to pass out the work to them, but since they're way more versed on updating their fork to work on more games they have way more chances of getting it to work than I do.
I guess you could also try their [latest releases](https://github.com/yukieiji/UnityExplorer/releases), but I doubt it would make any difference.
- The game is also online, right? Wouldn't be surprised if the devs encrypted the object store or object info on runtime to avoid cheating. EA has previously encrypted the games they published (even if they were single-player) which could be circumvented with MelonLoader, but since you are already using that I guess that won't fix it.

I am sorry I am not of much help! Please let me know if you try any of these things!

**Comment by AnticOwl** [comment]
Can you try ML 0.5.7? 
It worked for me for quite a lot of games.
